version: 2.1

orbs:
  android: circleci/android@2.3.0

executors:
  android-executor:
    docker:
      - image: cimg/android:2023.04
    environment:
      JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64

jobs:
  build:
    executor: android-executor
    steps:
      - checkout

      - restore_cache:
          key: android-gradle-cache-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}

      - run:
          name: Chmod permissions
          command: chmod +x ./gradlew 

      - run:
          name: Download Dependencies
          command: ./gradlew dependencies

      - save_cache:
          key: android-gradle-cache-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper

      - run:
          name: Run Build
          command: ./gradlew assembleDebug

      - store_artifacts:
          path: app/build/reports
          destination: reports

      - run:
          name: Run Tests
          command: ./gradlew lint test

      - store_test_results:
          path: app/build/test-results

      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: apk-debug
